# Version format
version: git-{build}

# Skip Github tags
skip_tags: true

# VM Template
image: Visual Studio 2015

# Clone depth
clone_depth: 1

# Branches to clone
branches:
  only:
    - master

# Environment variables
environment:
  matrix:
    - builder: msvc_ninja_64
      PYTHON: 'C:\\Python36-x64'
      BUILD_DIR: build
      NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip
    - builder: msvc_ninja_32
      PYTHON: 'C:\\Python36'
      BUILD_DIR: build
      NINJA_URL: https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip

# Required softwares for building
install:
  # Download required packages
  - cmd: if defined BUILD_DIR ( %PYTHON%\python.exe -m pip install meson && COPY %PYTHON%\Scripts\meson.py meson.py )
  - cmd: if defined NINJA_URL ( powershell -Command wget %NINJA_URL% -OutFile ninja.zip && unzip ninja.zip )

# Build scripts
build_script:
  - cmd: if %builder% == msvc_ninja_64 ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && %PYTHON%\\python.exe meson.py build && ninja -C build )

  - cmd: if %builder% == msvc_ninja_32 ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && %PYTHON%\\python.exe meson.py build && ninja -C build )

## Artifacts
#artifacts:
#  - path: sdb.exe 

