language: c
compiler:
  - gcc
  #- clang
  # With this scarry double quotation the strings will be passed to the shell
  # still quoted, which is necessary here.
  #- '"clang -fsanitize=address"'
  #- '"clang -fsanitize=memory -fsanitize-memory-track-origins"'
  #- '"clang -fsanitize=thread"'

env:
  - TESTS=test

script:
  # Limit the stack size (to 32MiB) to make ThreadSanitizer happy.
  - ulimit -s 32768
  # Now on to actually building stuff...
  - make clean
  - make
  - VERBOSE=1 make $TESTS
  # ----- NO_MMAN ----- #
  # Run again to find issues for the non-mmap build
  - make clean
  - git clean -xdf
  - CFLAGS=-DUSE_MMAN=0 make
  - VERBOSE=1 make $TESTS
  # Test install / uninstall procedures
  - sudo make install
  - sudo make uninstall
